sub:
	gcc -o sub.out subscriber.c subscriber_run_cmd.c subscriber_methods.c tcp_helpers.c common_utils.c

broker:
	gcc -o b.out broker.c tcp_helpers.c broker_sub_methods.c broker_pub_methods.c common_utils.c

pub:
	gcc -o pub.out publisher.c publisher_run_cmd.c publisher_methods.c tcp_helpers.c common_utils.c

