sub:
	gcc -o sub.out subscriber.c subscriber_run_cmd.c

broker:
	gcc -o b.out broker.c tcp_helpers.c broker_sub_methods.c

pub:
	gcc -o pub.out publisher.c publisher_run_cmd.c publisher_methods.c tcp_helpers.c
